postprocessor:
  name: nac
  APS_mode: True
  postprocessor_args:
    test_method: avg
    layer_names: [avgpool]
    valid_num: 1000
  layer_kwargs:
    avgpool:
      O: 10
      M: 50
      sig_alpha: 3000
      method: sigmoid(o*g_kl)
    layer3:
      O: 500
      M: 50
      sig_alpha: 300
      method: sigmoid(o*g_kl)
    layer2:
      O: 50
      M: 500
      sig_alpha: 0.01
      method: sigmoid(o*g_kl)
    layer1:
      O: 5000
      M: 1000
      sig_alpha: 1
      method: sigmoid(o*g_kl)
  postprocessor_sweep:
#     # Cross Entropy
    avgpool:
      O: [ 10, 50, 500]
      M: [ 50, 500 ]
      sig_alpha: [ 3000] # [1000, 3000, 5000]
      method: [sigmoid(o*g_kl)]
    layer3:
      O: [ 100, 500 ]
      M: [ 50, 500]
      sig_alpha: [50, 100, 300]
      method: [sigmoid(o*g_kl)]
    layer2:
      O: [ 50, 500 ]
      M: [ 500 ]
      sig_alpha: [0.01]
      method: [sigmoid(o*g_kl)]
    layer1:
      O: [ 5000 ]
      M: [ 500, 1000 ]
      sig_alpha: [ 0.1, 1]
      method: [sigmoid(o*g_kl)]
